// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUujA2eLaWExC9nQNJe2R9QrNINP8Nnyo',
    appId: '1:424148418575:web:2bfef60f0b90e151a4e37a',
    messagingSenderId: '424148418575',
    projectId: 'flux-e-commerce-app',
    authDomain: 'flux-e-commerce-app.firebaseapp.com',
    storageBucket: 'flux-e-commerce-app.firebasestorage.app',
    measurementId: 'G-21CWTVCB0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLVhIpMQ12qIfEkMUy-OxHB4fKWlxZkhA',
    appId: '1:424148418575:android:18271b2f125740efa4e37a',
    messagingSenderId: '424148418575',
    projectId: 'flux-e-commerce-app',
    storageBucket: 'flux-e-commerce-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCigyULD4OJV5YFXE9A4IWWgWNF1PqDE4o',
    appId: '1:424148418575:ios:f1a6adc739853e7da4e37a',
    messagingSenderId: '424148418575',
    projectId: 'flux-e-commerce-app',
    storageBucket: 'flux-e-commerce-app.firebasestorage.app',
    androidClientId: '424148418575-ol1kdcnsbksavs8fslm4fom7cvgtjviu.apps.googleusercontent.com',
    iosClientId: '424148418575-j175f7n8saflnfs4r2g00mi1nfvak8o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.depiGraduation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCigyULD4OJV5YFXE9A4IWWgWNF1PqDE4o',
    appId: '1:424148418575:ios:f1a6adc739853e7da4e37a',
    messagingSenderId: '424148418575',
    projectId: 'flux-e-commerce-app',
    storageBucket: 'flux-e-commerce-app.firebasestorage.app',
    androidClientId: '424148418575-ol1kdcnsbksavs8fslm4fom7cvgtjviu.apps.googleusercontent.com',
    iosClientId: '424148418575-j175f7n8saflnfs4r2g00mi1nfvak8o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.depiGraduation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUujA2eLaWExC9nQNJe2R9QrNINP8Nnyo',
    appId: '1:424148418575:web:bd841f3aa5ff34f1a4e37a',
    messagingSenderId: '424148418575',
    projectId: 'flux-e-commerce-app',
    authDomain: 'flux-e-commerce-app.firebaseapp.com',
    storageBucket: 'flux-e-commerce-app.firebasestorage.app',
    measurementId: 'G-VCB0G83FH6',
  );
}
