// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3sBKLoENseCGU3WVBkbILPaCVNFr5zGI',
    appId: '1:1091133489164:web:8ba743d917de86ba946e29',
    messagingSenderId: '1091133489164',
    projectId: 'socialfeedapp-77759',
    authDomain: 'socialfeedapp-77759.firebaseapp.com',
    storageBucket: 'socialfeedapp-77759.firebasestorage.app',
    measurementId: 'G-EN1BB9ZM46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcNdpYdUXfc5pHGnwC2gfooLMFSll-S4Q',
    appId: '1:1091133489164:android:9e135038b48eb8f1946e29',
    messagingSenderId: '1091133489164',
    projectId: 'socialfeedapp-77759',
    storageBucket: 'socialfeedapp-77759.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfTMNrqnj-5HGGGv92SQog8XFLz_V02Io',
    appId: '1:1091133489164:ios:1a09ce572c4fe304946e29',
    messagingSenderId: '1091133489164',
    projectId: 'socialfeedapp-77759',
    storageBucket: 'socialfeedapp-77759.firebasestorage.app',
    androidClientId: '1091133489164-lv02vqemarqf06afivpqlu4vl21klqtk.apps.googleusercontent.com',
    iosClientId: '1091133489164-o0ddqf30r9pgif0l3v52h2bai2e2teuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.depiGraduation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfTMNrqnj-5HGGGv92SQog8XFLz_V02Io',
    appId: '1:1091133489164:ios:1a09ce572c4fe304946e29',
    messagingSenderId: '1091133489164',
    projectId: 'socialfeedapp-77759',
    storageBucket: 'socialfeedapp-77759.firebasestorage.app',
    androidClientId: '1091133489164-lv02vqemarqf06afivpqlu4vl21klqtk.apps.googleusercontent.com',
    iosClientId: '1091133489164-o0ddqf30r9pgif0l3v52h2bai2e2teuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.depiGraduation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3sBKLoENseCGU3WVBkbILPaCVNFr5zGI',
    appId: '1:1091133489164:web:b0ac0d67232f6162946e29',
    messagingSenderId: '1091133489164',
    projectId: 'socialfeedapp-77759',
    authDomain: 'socialfeedapp-77759.firebaseapp.com',
    storageBucket: 'socialfeedapp-77759.firebasestorage.app',
    measurementId: 'G-K6VYVVKG8Y',
  );
}
